Add detailed characteristics for "JIRO", "Asana", "Nifty"
kol-oss/database-coursework pull request #4
Opened 2023-09-27 19:45 UTC by kovaliovev

- [x] Add detailed characteristic for "JIRO".
- [x] Add detailed characteristic for "Asana".
- [x] Add detailed characteristic for "Nifty".

2023-09-27 19:48 UTC, kol-oss approved these changes

2023-09-27 19:49 UTC, ipassternak approved these changes

2023-09-27 19:53 UTC, AndriiHalai commented on docs/requirements/state-of-the-art.md
> +[JIRA](https://www.atlassian.com/software/jira) — це широко використовуване програмне забезпечення для управління проектами та відстеження проблем, розроблене Atlassian. JIRA служить універсальною та
```suggestion
[JIRA](https://www.atlassian.com/software/jira) — це широко використовуване програмне забезпечення для управління проектами та відстеження проблем, розроблене Atlassian. JIRA є універсальною та комплексною платформою, розробленою для оптимізації управління проєктами, покращення співпраці та підвищення ефективності робочого процесу для організацій будь-якого розміру та галузі. Система створювалася як заміна Bugzilla й багато в чому повторює її архітектуру. Головними елементами JIRA є проблема(issue) і робочий процес(workflow). Issue описує роботу, яка має бути виконана, і може містити пріоритет, автора і позначення того, хто має над ним працювати.
```

2023-09-27 19:58 UTC, AndriiHalai requested changes

2023-09-27 19:58 UTC, AndriiHalai commented on docs/requirements/state-of-the-art.md
> +[JIRA](https://www.atlassian.com/software/jira) — це широко використовуване програмне забезпечення для управління проектами та відстеження проблем, розроблене Atlassian. JIRA служить універсальною та
```suggestion
[JIRA](https://www.atlassian.com/software/jira) — це широко використовуване програмне забезпечення для управління проектами та відстеження проблем, розроблене Atlassian. JIRA є універсальною та комплексною платформою, розробленою для оптимізації управління проєктами, покращення співпраці та підвищення ефективності робочого процесу для організацій будь-якого розміру та галузі. Система створювалася як заміна Bugzilla й багато в чому повторює її архітектуру. Головними елементами JIRA є проблема(issue) і робочий процес(workflow). Issue описує роботу, яка має бути виконана, і може містити пріоритет, автора і позначення того, хто має над ним працювати.
```

2023-09-27 19:58 UTC, AndriiHalai commented on docs/requirements/state-of-the-art.md
> +[Nifty](https://niftypm.com) — це хмарна платформа для управління проєктами та співпраці, яка відома своїм комплексним набором інструментів, призначених для спрощення та вдосконалення планування, від
```suggestion
[Nifty](https://niftypm.com) — це хмарна платформа для управління проєктами, яка відома своїм комплексним набором інструментів, призначених для спрощення та вдосконалення планування, відстеження та виконання проектів. Nifty пропонує поєднання інструментів відстеження завдань, спілкування та підвищення продуктивності в єдиній зручній платформі. Система призначена для обслуговування різноманітних галузей і команд, від стартапів до великих компаній, які прагнуть оптимізувати свої робочі процеси та покращити організацію проєктів.
```

2023-09-27 20:02 UTC, mari4kaa commented on docs/requirements/state-of-the-art.md
> +[JIRA](https://www.atlassian.com/software/jira) — це широко використовуване програмне забезпечення для управління проектами та відстеження проблем, розроблене Atlassian. JIRA служить універсальною та
> служить
It would be better to change it to 'слугує'.

2023-09-27 20:06 UTC, mari4kaa requested changes
>  JIRA служить універсальною та комплексною платформою

It would be better to change it to 'JIRA слугує універсальною та комплексною платформою'.

2023-09-28 05:56 UTC, kovaliovev commented on docs/requirements/state-of-the-art.md
> +[JIRA](https://www.atlassian.com/software/jira) — це широко використовуване програмне забезпечення для управління проектами та відстеження проблем, розроблене Atlassian. JIRA служить універсальною та
changed to "слугує"

2023-09-28 06:11 UTC, mari4kaa approved these changes

2023-09-28 06:15 UTC, AndriiHalai approved these changes

2023-09-28 06:16 UTC, merged