Horai
kol-oss/database-coursework pull request #44
Opened 2023-10-13 16:57 UTC by KseniiaHorai

2023-10-13 21:05 UTC, kol-oss requested changes

2023-10-13 21:05 UTC, kol-oss commented on docs/requirements/stakeholders-needs.md
> +         - RejectedAcess_EXC - користувач не має відповідного дозволу для видалення цієї задачі </br>
```suggestion
         - DeleteTask_RejectedAcess_EXC - користувач не має дозволу для видалення цієї задачі </br>
```

2023-10-13 21:05 UTC, kol-oss commented on docs/requirements/stakeholders-needs.md
> +            <li>Система відображає діалогове вікно для підтвердження операції видалення(можливий DeleteTask_CancelButton_EXC)</li>
```suggestion
            <li>Система відображає діалогове вікно для підтвердження операції видалення (можлива DeleteTask_CancelButton_EXC)</li>
```

2023-10-13 21:05 UTC, kol-oss commented on docs/requirements/stakeholders-needs.md
> +            <li>Система перевіряє права користувача (можливий RejectedAcess_EXC)</li>
```suggestion
            <li>Система перевіряє права користувача (можлива DeleteTask_RejectedAcess_EXC)</li>
```

2023-10-13 21:05 UTC, kol-oss commented on docs/requirements/stakeholders-needs.md
> +         -Виявлення підозрілої активності в обліковому записі користувача<br/>
```suggestion
         - Адміністратор виявив підозрілу активність користувача<br/>
```

2023-10-13 21:05 UTC, kol-oss commented on docs/requirements/stakeholders-needs.md
> +         - BanUser_CancelButton_EXC -адміністратор натиснув кнопку "Відміна"
```suggestion
         - BanUser_CancelButton_EXC - адміністратор натиснув кнопку "Відміна"
```

2023-10-13 21:05 UTC, kol-oss commented on docs/requirements/stakeholders-needs.md
> +          5. Адміністратор натискає кнопку "Підтвердити" (можливе BanUser_CancelButton_EXC)<br/>
```suggestion
          5. Адміністратор натискає кнопку "Підтвердити" (можлива BanUser_CancelButton_EXC)<br/>
```

2023-10-13 21:05 UTC, kol-oss commented on docs/requirements/stakeholders-needs.md
> +          3. Адміністратор натискає кнопку "Підтвердити" (можливий UnbanUser_CancelButton_EXC)<br/>
```suggestion
          3. Адміністратор натискає кнопку "Підтвердити" (можлива UnbanUser_CancelButton_EXC)<br/>
```

2023-10-13 21:05 UTC, kol-oss commented on docs/requirements/stakeholders-needs.md
> +          3. Адміністратор вирішує блокувати користувача<br/>
You can unite this steps

2023-10-13 21:28 UTC, kol-oss approved these changes

2023-10-13 21:31 UTC, mari4kaa commented on docs/requirements/stakeholders-needs.md
> +          3. Адміністратор вирішує блокувати користувача<br/>
Delete this step

2023-10-13 21:32 UTC, mari4kaa commented on docs/requirements/stakeholders-needs.md
> +          2. Адміністратор натискає на "Розблокувати користувача" <br/>
```suggestion
          2. Адміністратор натискає на кнопку "Розблокувати користувача" <br/>
```

2023-10-13 21:40 UTC, kol-oss requested changes

2023-10-13 21:40 UTC, kol-oss commented on docs/requirements/stakeholders-needs.md
> +          1. Адміністратор фіксує підозрілу активність користувача і блокує його<br/>
```suggestion
          1. Адміністратор фіксує підозрілу активність користувача<br/>
```

2023-10-14 07:40 UTC, kol-oss approved these changes

2023-10-14 07:41 UTC, merged