Add visualization of use cases: ApplyTemplateToProject, CreateProjectTemplate, DeleteProjectTemplate
kol-oss/database-coursework pull request #61
Opened 2023-10-18 14:44 UTC by kovaliovev

Add visualization of "ApplyTemplateToProject" use case.

2023-10-18 14:46 UTC, mari4kaa approved these changes

2023-10-18 22:01 UTC, kol-oss requested changes

2023-10-18 22:01 UTC, kol-oss commented on docs/use cases/README.md
> +:відкриває форму з підтвердженням\n видалення шаблону;
```suggestion
:Відкриває форму з підтвердженням\n видалення шаблону;
```

2023-10-19 10:27 UTC, kol-oss approved these changes

2023-10-19 10:27 UTC, merged